# Generated by Django 4.2.1 on 2024-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_skynews_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='skynews',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
